apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
    name: vllm-deepseek-r1-ep
spec:
    replicas: 1
    leaderWorkerTemplate:
        size: 2
        restartPolicy: None #RecreateGroupOnPodRestart

        workerTemplate:
            metadata:
              annotations:
                networking.gke.io/default-interface: 'eth0'
                networking.gke.io/interfaces: |
                  [
                    {"interfaceName":"eth0","network":"default"},
                    {"interfaceName":"eth2","network":"rdma-0"},
                    {"interfaceName":"eth3","network":"rdma-1"},
                    {"interfaceName":"eth4","network":"rdma-2"},
                    {"interfaceName":"eth5","network":"rdma-3"},
                    {"interfaceName":"eth6","network":"rdma-4"},
                    {"interfaceName":"eth7","network":"rdma-5"},
                    {"interfaceName":"eth8","network":"rdma-6"},
                    {"interfaceName":"eth9","network":"rdma-7"}
                  ]
            spec:
              containers:
              - name: vllm-worker
                # Use NVSHMEM 3.3.9 without the DeepEP patch to use DMABuf with CoS
                image: gcr.io/claytoncoleman-gke-dev/github.com/smarterclayton/vllm-dp-lws:main
                imagePullPolicy: Always
                workingDir: /code
                stdin: true
                tty: true
                command: ["/bin/bash","-c"]
                args:
                  - |
                    set -euo pipefail

                    if [[ -n "${DROP_KERNEL_CACHE}" ]]; then
                      rm -rf /root/.nv/ComputeCache/*
                    fi

                    # Debugging tools for the environment, libnl required for set_nccl_env.sh
                    if command -v apt-get >/dev/null 2>&1; then
                      # Using https://github.com/smarterclayton/vllm-dp-lws/tree/working_branch
                      apt-get install -y pciutils binutils kmod #gdb python3.12-dbg
                    fi

                    # Create ~/.bashrc so that kubectl exec -- /bin/bash is ready to run
                    cat <<'EOF' > ~/.bashrc
                    #!/bin/bash

                    bind '"\e[A":history-search-backward'
                    bind '"\e[B":history-search-forward'

                    shopt -s histappend
                    export HISTFILESIZE=1000000
                    export HISTSIZE=1000000
                    export HISTCONTROL=ignoreboth
                    shopt -s cmdhist

                    if command -v apt-get >/dev/null 2>&1; then
                      export VLLM_HOME=/app/venv
                    else
                      # Assume we're using the RH midstream image
                      export VLLM_HOME=/opt/vllm
                      export HF_HUB_OFFLINE=0
                    fi

                    # Configure gIB
                    export PATH=/usr/local/nvidia/bin:${PATH}:/usr/local/gib/bin
                    source /usr/local/gib/scripts/set_nccl_env.sh
                    unset NCCL_NET
                    export NCCL_NET_PLUGIN=/usr/local/gib/lib64/libnccl-net_internal.so
                    export START_RANK=$(( ${LWS_WORKER_INDEX:-0} * DP_SIZE_LOCAL ))

                    if [ "${LWS_WORKER_INDEX:-0}" -eq 0 ]; then
                      #################
                      # Leader-only launch
                      #################
                      serve=(
                      ${VLLM_HOME}/bin/vllm serve \
                        deepseek-ai/DeepSeek-R1 \
                        --port 8000 \
                        --enforce-eager \
                        --disable-log-requests \
                        --enable-expert-parallel \
                        --tensor-parallel-size $TP_SIZE \
                        --data-parallel-size $DP_SIZE \
                        --data-parallel-size-local $DP_SIZE_LOCAL \
                        --data-parallel-address ${LWS_LEADER_ADDRESS} \
                        --data-parallel-rpc-port 5555 \
                        --data-parallel-start-rank $START_RANK \
                        --trust-remote-code
                      )
                    else
                      #################
                      # Worker-only launch
                      #################
                      serve=(
                      ${VLLM_HOME}/bin/vllm serve \
                        deepseek-ai/DeepSeek-R1 \
                        --port 8000 \
                        --enforce-eager \
                        --disable-log-requests \
                        --enable-expert-parallel \
                        --tensor-parallel-size $TP_SIZE \
                        --data-parallel-size $DP_SIZE \
                        --data-parallel-size-local $DP_SIZE_LOCAL \
                        --data-parallel-address ${LWS_LEADER_ADDRESS} \
                        --data-parallel-rpc-port 5555 \
                        --data-parallel-start-rank $START_RANK \
                        --trust-remote-code \
                        --headless
                      )
                    fi

                    # Run a benchmark that is decode-only
                    function bench_decode {
                      VIRTUAL_ENV=/app/venv uv run /app/vllm/benchmarks/benchmark_serving.py --base-url http://${LWS_LEADER_ADDRESS}:8000 --model deepseek-ai/DeepSeek-R1 --dataset-name random --random-input-len 1 --random-output-len 1000 --seed $(date +%M%H%M%S) --num-prompts 512 --ignore-eos
                    }
                    # Run a benchmark with mixed prefill and decode
                    function bench_mixed {
                      VIRTUAL_ENV=/app/venv uv run /app/vllm/benchmarks/benchmark_serving.py --base-url http://${LWS_LEADER_ADDRESS}:8000 --model deepseek-ai/DeepSeek-R1 --dataset-name random --random-input-len 100 --random-output-len 1000 --max-concurrency 512 --seed $(date +%M%H%M%S) --num-prompts 512 --ignore-eos
                    }
                    # Start Qwen3 for a faster and simpler MoE test harness
                    function serve_simple {
                      ${VLLM_HOME}/bin/vllm serve Qwen/Qwen3-30B-A3B-FP8 --port 8000 --enforce-eager --disable-log-requests --enable-expert-parallel --tensor-parallel-size 1 --data-parallel-size 2 --trust-remote-code
                    }
                    # Execute DeepEP's internode latency and tuning test
                    function test_internode {
                      VIRTUAL_ENV=/app/venv WORLD_SIZE=$(( ${DP_SIZE} / ${DP_SIZE_LOCAL} )) MASTER_ADDR=${LWS_LEADER_ADDRESS} RANK=$(( ${START_RANK} / ${DP_SIZE_LOCAL} )) uv run /app/DeepEP/tests/test_internode.py
                    }
                    EOF

                    ######################
                    # INSTALL Dependencies
                    ######################
                    for script in deepgemm vllm; do
                      branch="${script^^}_BRANCH"
                      if [[ -z "${!branch-}" ]]; then
                        continue
                      fi
                      for location in /init-scripts /install-scripts; do
                        if [[ -f ${location}/${script}.sh ]]; then
                          ${location}/${script}.sh
                          break
                        fi
                      done
                    done

                    # Hold the container before launch to allow debugging
                    if [[ -n "${INTERACTIVE:-}" ]]; then
                      echo "Waiting for /code/launch to run vLLM"
                      while [[ ! -f /code/launch ]]; do
                        sleep 10
                      done
                      rm /code/launch
                    fi

                    source ~/.bashrc
                    env | sort
                    exec "${serve[@]}"
                env:
                  - name: INTERACTIVE
                    value: ""
                  - name: DROP_KERNEL_CACHE
                    value: ""

                  # Use a recent vLLM commit that is known working
                  - name: VLLM_REPO_URL
                    value: "https://github.com/vllm-project/vllm.git"
                  - name: VLLM_BRANCH
                    value: "main"
                  # - name: VLLM_COMMIT
                    value: "4da8bf20d08f1f8f97a4839d580eb923d0ca9415" # known working
                    # value: "eec890c1c1cdf6d4bbf4c0563fac54abe80ab8b6" # https://github.com/vllm-project/vllm/pull/22399
                    # value: "6d8d0a24c02bfd84d46b3016b865a44f048ae84b" # v0.10.0
                  - name: DEEPGEMM_REPO_URL
                    value: "https://github.com/deepseek-ai/DeepGEMM.git" 
                  - name: DEEPGEMM_BRANCH
                    value: "main"
                  - name: DEEPGEMM_COMMIT
                    value: "7b6b5563b9d4c1ae07ffbce7f78ad3ac9204827c" # https://github.com/deepseek-ai/DeepGEMM/pull/154
                  # Ensure we are using the latest flashinfer until we fix the crash
                  - name: FLASHINFER_BRANCH
                    value: "main"

                  - name: LD_LIBRARY_PATH
                    value: /opt/nvshmem-3.3.9/lib:/usr/local/nixl/lib/x86_64-linux-gnu:/opt/ucx/lib:/usr/local/lib:/usr/local/gib/lib64:/usr/local/nvidia/lib64:/usr/local/cuda/lib64

                  # Networking config
                  - name: NVSHMEM_REMOTE_TRANSPORT
                    value: "ibgda"
                  - name: NVSHMEM_IB_ENABLE_IBGDA
                    value: "true"
                  # Currently disabled as we don't mount /dev/gdrdrv into the container
                  - name: NVIDIA_GDRCOPY
                    value: "disabled"
                  - name: NVSHMEM_BOOTSTRAP_UID_SOCK_IFNAME
                    value: "eth0"
                  - name: GLOO_SOCKET_IFNAME
                    value: "eth0"

                  # Debugging info
                  - name: UCX_LOG_LEVEL
                    value: "debug"
                  - name: NVSHMEM_INFO
                    value: "true"
                  - name: NVSHMEM_DEBUG
                    value: "DEBUG"
                  - name: NVSHMEM_DEBUG_SUBSYS
                    value: "ALL"
                  - name: VLLM_TORCH_PROFILER_DIR
                    value: "/code/traces"
                  - name: NCCL_DEBUG
                    value: INFO # trace
                  - name: VLLM_LOGGING_LEVEL
                    value: "DEBUG"
                  - name: HF_HUB_DISABLE_PROGRESS_BARS
                    value: "1"
                  # - name: CUDA_LAUNCH_BLOCKING
                  #   value: "1"

                  # DP/EP configuration in vLLM
                  - name: VLLM_USE_DEEP_GEMM
                    value: "1"
                  - name: VLLM_ALL2ALL_BACKEND
                    # value: "naive"
                    # value: "pplx"
                    # value: "deepep_high_throughput"
                    value: "deepep_low_latency"
                  # Enabling the Cutlass kernels for attention improves decode perf by about 10%,
                  # but there is an intermittent hang that seems to be triggered by enabling this path.
                  # - name: VLLM_ATTENTION_BACKEND
                  #   value: CUTLASS_MLA
                  - name: VLLM_RANDOMIZE_DP_DUMMY_INPUTS
                    value: "1"
                  - name: DP_SIZE
                    value: "16"
                  - name: TP_SIZE
                    value: "1"
                  - name: DP_SIZE_LOCAL
                    value: "8"
                  - name: VLLM_NIXL_SIDE_CHANNEL_PORT
                    value: "6555"
                  - name: VLLM_NIXL_SIDE_CHANNEL_HOST
                    valueFrom:
                      fieldRef:
                        fieldPath: status.podIP

                  # Cache FlashInfer JIT into the ComputeCache mount as well
                  - name: FLASHINFER_WORKSPACE_BASE
                    value: /root/.nv/ComputeCache
                  - name: HF_HUB_CACHE
                    value: /huggingface-cache
                  - name: HF_TOKEN
                    valueFrom:
                      secretKeyRef:
                        name: hf-secret
                        key: HF_TOKEN
                        optional: true
                  - name: GH_TOKEN_FROM_SECRET
                    valueFrom:
                      secretKeyRef:
                        name: gh-token-secret
                        key: GH_TOKEN
                        optional: true

                  # Configuration for building and configuring torch
                  - name: MAX_JOBS
                    value: "128"
                  - name: TORCH_CUDA_ARCH_LIST
                    value: "9.0a 10.0"

                # may not be needed on GKE
                securityContext:
                  runAsUser: 0  # needed for RH image to be able to override files (runs as vllm)
                  privileged: true # needed to open the host device for UAR ??
                  capabilities:
                    add:
                    - "IPC_LOCK"
                    - "SYS_RAWIO"
                resources:
                  limits:
                    memory: 512Gi
                    ephemeral-storage: 3Ti
                    nvidia.com/gpu: "8"
                    
                    networking.gke.io.networks/rdma-0: "1"
                    networking.gke.io.networks/rdma-0.IP: "1"
                    networking.gke.io.networks/rdma-1: "1"
                    networking.gke.io.networks/rdma-1.IP: "1"
                    networking.gke.io.networks/rdma-2: "1"
                    networking.gke.io.networks/rdma-2.IP: "1"
                    networking.gke.io.networks/rdma-3: "1"
                    networking.gke.io.networks/rdma-3.IP: "1"
                    networking.gke.io.networks/rdma-4: "1"
                    networking.gke.io.networks/rdma-4.IP: "1"
                    networking.gke.io.networks/rdma-5: "1"
                    networking.gke.io.networks/rdma-5.IP: "1"
                    networking.gke.io.networks/rdma-6: "1"
                    networking.gke.io.networks/rdma-6.IP: "1"
                    networking.gke.io.networks/rdma-7: "1"
                    networking.gke.io.networks/rdma-7.IP: "1"                    
                  requests:
                    cpu: 32
                    memory: 512Gi
                    ephemeral-storage: 3Ti
                    nvidia.com/gpu: "8"

                    networking.gke.io.networks/rdma-0: "1"
                    networking.gke.io.networks/rdma-0.IP: "1"
                    networking.gke.io.networks/rdma-1: "1"
                    networking.gke.io.networks/rdma-1.IP: "1"
                    networking.gke.io.networks/rdma-2: "1"
                    networking.gke.io.networks/rdma-2.IP: "1"
                    networking.gke.io.networks/rdma-3: "1"
                    networking.gke.io.networks/rdma-3.IP: "1"
                    networking.gke.io.networks/rdma-4: "1"
                    networking.gke.io.networks/rdma-4.IP: "1"
                    networking.gke.io.networks/rdma-5: "1"
                    networking.gke.io.networks/rdma-5.IP: "1"
                    networking.gke.io.networks/rdma-6: "1"
                    networking.gke.io.networks/rdma-6.IP: "1"
                    networking.gke.io.networks/rdma-7: "1"
                    networking.gke.io.networks/rdma-7.IP: "1"
                volumeMounts:
                  - name: dshm
                    mountPath: /dev/shm
                  - name: init-scripts-volume
                    mountPath: /init-scripts
                  - name: hf-cache
                    mountPath: /huggingface-cache
                  - name: nv-compute-cache
                    mountPath: /root/.nv/ComputeCache
                  - name: vllm
                    mountPath: /code
                  # Required to access the gIB configuration for NCCL
                  - mountPath: /usr/local/gib
                    name: gib
              volumes:
                # Volume for the init script from ConfigMap
                - name: init-scripts-volume
                  configMap:
                    name: vllm-init-scripts-config
                    defaultMode: 0755 # Set execute permissions for the script
                    optional: true
                # Needed for NCCL to function
                - name: dshm
                  emptyDir:
                    medium: Memory
                    sizeLimit: 1Gi
                # Use a durable hf cache on the SSD to avoid redownloading large models
                - name: hf-cache
                  hostPath:
                    path: /mnt/stateful_partition/kube-ephemeral-ssd/shared_disk/hfcache/
                    type: DirectoryOrCreate
                - name: nv-compute-cache
                  hostPath:
                    path: /mnt/stateful_partition/kube-ephemeral-ssd/shared_disk/nv-compute-cache
                    type: DirectoryOrCreate
                - name: vllm
                  emptyDir: {}
                # Necessary for gIB
                - name: gib
                  hostPath:
                    path: /home/kubernetes/bin/gib
                    type: ""
