kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-exec
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-exec-service-account-default
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: pod-exec
  apiGroup: rbac.authorization.k8s.io