kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: root
spec:
  selector:
    matchLabels:
      app: root-shell
  template:
    metadata:
      labels:
        app: root-shell
    spec:
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      containers:
      - name: shell
        image: gke.gcr.io/pause:3.8
        command:
        - /bin/sh
        - -c
        - sleep infinity
        volumeMounts:
        - mountPath: /
          name: root
        securityContext:
          runAsUser: 0
          privileged: true
      volumes:
      - name: root
        hostPath:
          path: /
