apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceModel
metadata:
  name: summarizer
spec:
  criticality: Sheddable
  modelName: summarizer
  targetModels:
  - name: meta-llama/Llama-3.1-8B-Instruct
  poolRef:
    group: inference.networking.x-k8s.io
    kind: InferencePool
    name: vllm-llama3-8b-instruct
